name: CI
on: [push, pull_request]

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$Env:HAXE_STD_PATH\.." >> $Env:GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib git format https://github.com/codescapade/format --quiet
          haxelib git haxetoml https://github.com/codescapade/haxetoml --quiet
          haxelib install buddy 2.13.0 --quiet

      - name: Run Tests
        run: haxe tests.hxml



  build-windows:
    needs: run-tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$Env:HAXE_STD_PATH\.." >> $Env:GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib git format https://github.com/codescapade/format --quiet
          haxelib git haxetoml https://github.com/codescapade/haxetoml --quiet

      - name: Build Aeons Atlas
        run: haxe build-windows.hxml

      - uses: actions/upload-artifact@v2
        with:
          name: AeonsAtlas-Windows
          path: build\windows\AeonsAtlasWin.exe
          if-no-files-found: error

  build-macos:
    needs: run-tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$Env:HAXE_STD_PATH\.." >> $Env:GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib git format https://github.com/codescapade/format --quiet
          haxelib git haxetoml https://github.com/codescapade/haxetoml --quiet

      - name: Build Aeons Atlas
        run: haxe build-macos.hxml

      - name: Make executable
        run: chmod +x build/macos/AeonsAtlasMac

      - uses: actions/upload-artifact@v2
        with:
          name: AeonsAtlas-MacOS
          path: build/macos/AeonsAtlasMac
          if-no-files-found: error


  build-linux:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$Env:HAXE_STD_PATH\.." >> $Env:GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib git format https://github.com/codescapade/format --quiet
          haxelib git haxetoml https://github.com/codescapade/haxetoml --quiet

      - name: Build Aeons Atlas
        run: haxe build-linux.hxml

      - name: Make executable
        run: chmod +x build/linux/AeonsAtlasLinux

      - uses: actions/upload-artifact@v2
        with:
          name: AeonsAtlas-Linux
          path: build/linux/AeonsAtlasLinux
          if-no-files-found: error
